$(document).ready(function(){
    $(".menu ul .m").click(function(){
		 $("#icon4").show();
		 $("#icon6").show();
		  $("#icona").show();
		  $("#iconc").show();
		  $("#iconbc").show();
		$("#iconde").hide();
		   $("#icond").hide();
		   $("#iconb").hide();
		 $("#icon5").hide();
		 $("#icon7").hide();
		$("#icon2").toggle();
		$("#icon3").toggle();
        $(".menu ul li ul .n").slideToggle(1000);
		$(".menu ul li ul .p").hide(1000);
		 $(".menu ul li ul .r").hide(1000);
		 $(".menu ul li ul .t").hide(1000);
		 $(".menu ul li ul .v").hide(1000);
		 $(".menu ul li ul .vw").hide(1000);
    });
	 $(".menu ul .o").click(function(){
		 $("#icon2").show();
		 $("#icon6").show();
		  $("#icona").show();
		  $("#iconc").show();
		  $("#iconbc").show();
		$("#iconde").hide();
		   $("#iconb").hide();
		   $("#icond").hide();
		 $("#icon3").hide();
		 $("#icon7").hide();
		$("#icon4").toggle();
		$("#icon5").toggle();
        $(".menu ul li ul .p").slideToggle(1000);
		$(".menu ul li ul .n").hide(1000);
		 $(".menu ul li ul .r").hide(1000);
		 $(".menu ul li ul .t").hide(1000);
		 $(".menu ul li ul .v").hide(1000);
		 $(".menu ul li ul .vw").hide(1000);
    });
	 $(".menu ul .q").click(function(){
		 $("#icon2").show();
		 $("#icon4").show();
		 $("#icona").show();
		 $("#iconc").show();
		$("#iconbc").show();
		$("#iconde").hide();
		   $("#icond").hide();
		 $("#icon3").hide();
		 $("#iconb").hide();
		 $("#icon5").hide();
		$("#icon6").toggle();
		$("#icon7").toggle();
        $(".menu ul li ul .r").slideToggle(1000);
		$(".menu ul li ul .n").hide(1000);
		$(".menu ul li ul .p").hide(1000);
		$(".menu ul li ul .t").hide(1000);
		$(".menu ul li ul .v").hide(1000);
		$(".menu ul li ul .vw").hide(1000);
    });
	 $(".menu ul .s").click(function(){
		 $("#icon2").show();
		 $("#icon4").show();
		 $("#icon6").show();
		 $("#iconc").show();
		$("#iconbc").show();
		$("#iconde").hide();
		   $("#icond").hide();
		 $("#icon3").hide();
		 $("#icon5").hide();
		 $("#icon7").hide();
		 $("#icond").hide();
		$("#icona").toggle();
		$("#iconb").toggle();
        $(".menu ul li ul .t").slideToggle(1000);
		$(".menu ul li ul .n").hide(1000);
		$(".menu ul li ul .p").hide(1000);
		$(".menu ul li ul .r").hide(1000);
		$(".menu ul li ul .v").hide(1000);
		$(".menu ul li ul .vw").hide(1000);
    });
	 $(".menu ul .u").click(function(){
		 $("#icon2").show();
		 $("#icon4").show();
		 $("#icon6").show();
		 $("#icona").show();
		 $("#iconbc").show();
		$("#iconde").hide();
		 $("#icon3").hide();
		 $("#icon5").hide();
		 $("#icon7").hide();
		 $("#iconb").hide();
		$("#iconc").toggle();
		$("#icond").toggle();
        $(".menu ul li ul .v").slideToggle(1000);
		$(".menu ul li ul .n").hide(1000);
		$(".menu ul li ul .p").hide(1000);
		$(".menu ul li ul .r").hide(1000);
		$(".menu ul li ul .t").hide(1000);
		 $(".menu ul li ul .vw").hide(1000);
    });
	 $(".menu ul .uv").click(function(){
		 $("#icon2").show();
		 $("#icon4").show();
		 $("#icon6").show();
		 $("#icona").show();
		 $("#iconc").show();
		$("#icond").hide();
		 $("#icon3").hide();
		 $("#icon5").hide();
		 $("#icon7").hide();
		 $("#iconb").hide();
		$("#iconbc").toggle();
		$("#iconde").toggle();
        $(".menu ul li ul .vw").slideToggle(1000);
		$(".menu ul li ul .n").hide(1000);
		$(".menu ul li ul .p").hide(1000);
		$(".menu ul li ul .r").hide(1000);
		 $(".menu ul li ul .t").hide(1000);
    });
});
